/**
 * @file Static datrabase of Pinpons
 * for prototype demonstation purposes
 */

import type { Pinpon } from "../../common/Pinpon";

export const pinpons: Pinpon[] = [
  {
    title: "New York from above",
    author: "Leyre",
    unsplash: "71SHXwBLp5w",
    interests: ["Future"],
  },
  {
    title: "Not Bound by Rules",
    author: "Josh Hild",
    unsplash: "WjZ4eaHq9G4",
    interests: ["Future", "Technology"],
  },
  {
    title: "Goggles",
    author: "Ameer Basheer",
    unsplash: "2r5adxul49E",
    interests: ["Future", "Technology"],
  },
  {
    title: "Flume in Switzerland",
    author: "Fabio",
    unsplash: "oyXis2kALVg",
    interests: ["Future"],
  },
  {
    title: "Future led",
    author: "Steven Ramon",
    unsplash: "ODbOdeQVF2Q",
    interests: ["Future"],
  },
  {
    title: "Redline I",
    author: "Fakurian Design",
    unsplash: "wNsHBf_bTBo",
    interests: ["Future"],
  },
  {
    title: "Prosthetic arm visualization",
    author: "ThisisEngineering RAEng",
    unsplash: "sbVu5zitZt0",
    interests: ["Future", "Technology"],
  },
  {
    title: "Boy and gril sharing a connection",
    author: "Noah Buscher",
    unsplash: "7j8Ls1EVImA",
    interests: ["Future"],
  },
  {
    title: "Boards",
    author: "Adi Goldstein",
    unsplash: "EUsVwEOsblE",
    interests: ["Future", "Technology"],
  },
  {
    title: "Rise Up Hand (dark glow edition)",
    author: "Nitish Gowswami",
    unsplash: "0DrOxIiOu0Q",
    interests: ["Future"],
  },
  {
    title: "Terminal and skyscrapers",
    author: "Luca Bravo",
    unsplash: "a6x7YPiNxwI",
    interests: ["Future"],
  },
  {
    title: "Dominion tower",
    author: "Egor Vikhrev",
    unsplash: "g5W0y1s6Sr8",
    interests: ["Future"],
  },
  {
    title: "Rave Russia",
    author: "Alexander Popov",
    unsplash: "3InMDrsuYrk",
    interests: ["Future"],
  },
  {
    title: "Dyson sphere",
    author: "Salvatore Andrea Santacroce",
    unsplash: "wGICoyAhEs4",
    interests: ["Future"],
  },
  {
    title: "Blue Astronaut 04",
    author: "Elia Pellegrini",
    unsplash: "YJHgXGfMePk",
    interests: ["Future"],
  },
  {
    title: "What does future hold?",
    author: "Alex Iby",
    unsplash: "9-ZsdNfxfr4",
    interests: ["Future", "Technology"],
  },
  {
    title: "Mini computer",
    author: "Lorenzo Harrera",
    unsplash: "p0j-mE6mGo4",
    interests: ["Technology"],
  },
  {
    title: "Eat, sleep, neon, repeat",
    author: "Manny Moreno",
    unsplash: "Wxq7U4jaPfM",
    interests: ["Future", "Technology"],
  },
  {
    title: "MacBook",
    author: "Ales Nesetril",
    unsplash: "Im7lZjxeLhg",
    interests: ["Technology"],
  },
  {
    title: "Virtual Reality",
    author: "Maxim Hopman",
    unsplash: "8vn4KvfU640",
    interests: ["Technology"],
  },
  {
    title: "Quest",
    author: "Minh Pham",
    unsplash: "HI6gy-p-WBI",
    interests: ["Technology"],
  },
  {
    title: "Haning camera",
    author: "Arturo Ochoa",
    unsplash: "c5rnWNjtmmM",
    interests: ["Privacy"],
  },
  {
    title: "TOCABI humanoid arm",
    author: "Mather Schwartz",
    unsplash: "zIIXVa5BwvM",
    interests: ["Technology"],
  },
  {
    title: "Iphone",
    author: "March Chan",
    unsplash: "-BD3cWCkVTs",
    interests: ["Technology"],
  },
  {
    title: "Survailance",
    author: "Lianhao Qu",
    unsplash: "LfaN1gswV5c",
    interests: ["Privacy"],
  },
  {
    title: "Women look at security cameras",
    author: "Matthew Henry",
    unsplash: "fPxOowbR6ls",
    interests: ["Privacy"],
  },
  {
    title: "Painting of survailance",
    author: "Tobias Tullius",
    unsplash: "4dKy7d3lkKM",
    interests: ["Privacy"],
  },
  {
    title: "Passlock",
    author: "Towfiqu Barbhuiya",
    unsplash: "FnA5pAzqhMM",
    interests: ["Privacy"],
  },
  {
    title: "Classified newspaper page",
    author: "Absolut Vision",
    unsplash: "bSlHKWxxXak",
    interests: ["Privacy"],
  },
  {
    title: "Private",
    author: "Dayne Topkin",
    unsplash: "u5Zt-HoocrM",
    interests: ["Privacy"],
  },
  {
    title: "Survailance cameras",
    author: "Arthur Mazi",
    unsplash: "a8CxRWIu8yw",
    interests: ["Privacy"],
  },
  {
    title: "Lone survailance camera",
    author: "Maximalfocus",
    unsplash: "QtZDb5QJOFM",
    interests: ["Privacy"],
  },
  {
    title: "Qwerasdzx",
    author: "Muhannad Ajjan",
    unsplash: "sL2BRR1cuvM",
    interests: ["Technology", "Computer games"],
  },
  {
    title: "ROG 02",
    author: "Axville",
    unsplash: "WcrqKjgMPfI",
    interests: ["Computer games", "Technology"],
  },
  {
    title: "Overwatch",
    author: "Florian Olivo",
    unsplash: "Mf23RF8xArY",
    interests: ["Computer games"],
  },
  {
    title: "Person with headphones",
    author: "Fredrick Tendong",
    unsplash: "-GMUHeFuJUs",
    interests: ["Computer games"],
  },
  {
    title: "Razor gaming neon keyboard",
    author: "Christopher Farrugia",
    unsplash: "2yQtqBqzDRo",
    interests: ["Computer games", "Technology"],
  },
  {
    title: "An original title",
    author: "Amine Rock Hoovr",
    unsplash: "qoeU4a6psaQ",
    interests: ["Computer games"],
  },
  {
    title: "Fortnite loading screen",
    author: "Vlad Goshkov",
    unsplash: "G1jbCAqp5sk",
    interests: ["Computer games"],
  },
  {
    title: "Controller",
    author: "Jakub Sisulak",
    unsplash: "L1AEdl-iLL4",
    interests: ["Computer games"],
  },
  {
    title: "Gamers",
    author: "Fredrick Tendong",
    unsplash: "13aw-Pwdeqk",
    interests: ["Computer games"],
  },
  {
    title: "Original design",
    author: "Amelie Mourichon",
    unsplash: "sv8oOQaUb-o",
    interests: ["Design"],
  },
  {
    title: "UX Work",
    author: "Kelly Sikkema",
    unsplash: "gcHFXsdcmJE",
    interests: ["Design"],
  },
  {
    title: "Google material design",
    author: "Tirza van Dijk",
    unsplash: "o1SKqmgSDbg",
    interests: ["Design"],
  },
  {
    title: "Drawing wireframe",
    author: "Kelly Sikkema",
    unsplash: "v9FQR4tbIq8",
    interests: ["Design"],
  },
  {
    title: "Sketching",
    author: "Hal Gatewood",
    unsplash: "tZc3vjPCk-Q",
    interests: ["Design"],
  },
  {
    title: "Portfolio",
    author: "Ben Kolde",
    unsplash: "bs2Ba7t69mM",
    interests: ["Design"],
  },
  {
    title: "Icon design",
    author: "Harpal Singh",
    unsplash: "_zKxPsGOGKg",
    interests: ["Design"],
  },
  {
    title: "Wireframing",
    author: "Sigmund",
    unsplash: "4UGmm3WRUoQ",
    interests: ["Design"],
  },
  {
    title: "Phone portfolio",
    author: "Ben Kolde",
    unsplash: "cpLsWmMEa1Q",
    interests: ["Design"],
  }
];
